###
# In another terminal, trigger self-play
POST http://localhost:8000/api/v1/self-play/start
Content-Type: application/json

{
  "num_games": 1000,
  "difficulty_x": "hard",
  "difficulty_o": "hard",
  "add_noise": true
}


###
GET http://localhost:8000/api/v1/self-play/status/e5e057be-e684-4552-adc1-a70784d254f5
Content-Type: application/json"


###

POST http://localhost:8000/api/v1/datasets/export
Content-Type: application/json

{
  "format": "parquet",
  "max_games": 1000
}

###

GET http://localhost:8000/api/v1/datasets/stats
Content-Type: application/json